### ISSUE TITLE
The letter "ș" is transformed to an image when running make4ht without the agrument --xetex

### ISSUE THREAD

**Issue by gamboz** [michal-h21/make4ht#157]
I have the following MWE:
```tex
\documentclass{article}
\begin{document}
LATIN SMALL LETTER S WITH COMMA BELOW

ș
\end{document}
```

if I compile it as `make4ht x.tex` I get the following (edited for clarity):
```html
...<img alt='s,' src='x0x.png' />...
```

which is not wrong, however, if I compile the same file with as `make4ht --xetex x.tex` I get:
```html
... ș ...
```

which is "more" correct :slightly_smiling_face: 

So my question is if it might be possible to get the "ș" directly even with non-xetex compilation.

I ask because we use `mak4ht` as part of workflow which is always delicate to change...

(I tried to look at `.../tex/generic/tex4ht/unicode.4ht` but wasn't able to understand it)

**Comment by michal-h21** [comment]
Thanks for the report. Without the `-x` or `-l` options, we use the original LaTeX definition of this character, which stacks a comma under the "s" character using `\oalign`, which produces an image. 

I will fix this in TeX4ht sources. In the meantime, you can use this config file:

```latex
\Preamble{xhtml}
\catcode`\:=11

\def\:tempa#1{%
\ifcsname textcommabelow-#1\endcsname%
\protect\leavevmode\ht:special{t4ht@+\string&{35}x\csname textcommabelow-#1\endcsname{59}}x%
\else%
\o:textcommabelow:{#1}%
\fi%
}

\HLet\textcommabelow\:tempa

\catcode`\:=12


\NewConfigure{textcommabelow}[2]{%
  \expandafter\def\csname textcommabelow-#1\endcsname{#2}%
}
\Configure{textcommabelow}{S}{0218}
\Configure{textcommabelow}{s}{0219}
\Configure{textcommabelow}{T}{021A}
\Configure{textcommabelow}{t}{021B}
\begin{document}
\EndPreamble

```
It provides configuration for characters defined by LaTeX core which use the `\textcommabelow` command. The code is a bit complicated, because we need to support these characters inside pictures.

**Comment by gamboz** [comment]
[OT] thanks for all the work you and your colleagues do on tex4ht!

**Comment by michal-h21** [comment]
Thank you so much! It’s always great to hear that the work we do is appreciated.

Can I close this issue now?

**Comment by gamboz** [comment]
Yes (closing)
