### ISSUE TITLE
unbalanced tag </mrow

### ISSUE THREAD

**Issue by touhami** [michal-h21/make4ht#34]
When I try to compile the folloing MWE with the command `make4ht -u myfile.tex "mathml,
mathjax`

```
\documentclass{article}
\usepackage{amsmath}

\begin{document}

\[\begin{cases} % no problem
x & x\in A\\
y & x\in B.
\end{cases}\]

\[\begin{cases}
x & x\in A\\
y & x\in ]a,b[.
\end{cases}\]

\[\begin{cases}
x & x\in ]a,b[\\
y & x\in B.
\end{cases}\]
\end{document}
```
I get a warning about `unbalanced tag </mrow` and the result of the last two formula is wrong.

![1](https://user-images.githubusercontent.com/8748459/91205087-e963cb80-e6fc-11ea-8155-623c43f79276.png)

**Comment by michal-h21** [comment]
You can try to use the `mathml-` [option](https://www.kodymirus.cz/tex4ht-doc/texfourhtOptions.html) instead:

   make4ht myfile.tex "mathml-,mathjax"

It uses slightly different configuration for brackets. [Here](https://puszcza.gnu.org.ua/bugs/?278) are some more details.

**Comment by touhami** [comment]
Great. Is there a way to know when one should use this option or it's always ok.

off-topic: why did you write 

`make4ht myfile.tex "mathml-,mathjax"`

 and not 

`make4ht -u myfile.tex "mathml-,mathjax" `

 i mean why not `-u`? are you recommending it or just ignored?

**Comment by michal-h21** [comment]
I've just updated TeX4ht sources to use the relevant code from `mathml-` option by default for MathML output. So you should get correct result even with `mathml` option. The `mathml-` option produces code, that sometimes isn't that semantically correct and it may have wrong rendering. But this particular  code seems to work well and should be really used by default, as it can fix lot of issues like this one.

The `-u` option is obsolete, because `utf8` output is produced by default now.

**Comment by touhami** [comment]
Great. Thank you.

**Comment by michal-h21** [comment]
OK, so I hope we can close this for now :)
