### ISSUE TITLE
Fixligatures doesn't work with fourier

### ISSUE THREAD

**Issue by vonbrand** [michal-h21/make4ht#35]
I'm using `make4ht -u -f html,mathml+fixligatures ligatures.tex`, and get a mangled HTM file as a result (ligatures are just deleted).
[test.zip](https://github.com/michal-h21/make4ht/files/5142932/test.zip) contains the minimal LaTeX source and result.

**Comment by michal-h21** [comment]
The issue is that there are no font mapping files for Fourier fonts. So you get only the basic characters, but ligatures are ignored and some other characters can be converted incorrectly.

I've created mappings using [Htfgen](https://github.com/michal-h21/htfgen) tool. It reported some issues, but it seems to work for ligatures and basic math. 

[Here](https://gist.github.com/michal-h21/773259d1998eec82ca0fea80a405ad7e) is a TeX file that can be used to generate mappings. Place it to the directory with your TeX file and compile it using `etex fourier.tex`. It will create lot of files with the `.htf` extension. These are the mapping files. If everything works correctly, I will update TeX4ht sources.

**Comment by vonbrand** [comment]
It worked! Thanks.

Only a warning that auxhook can't patch document using \AtBeginDocument instead

**Comment by michal-h21** [comment]
I've added the Fourier fonts to TeX4ht sources, so it should be all available soon.

What is the exact warning you get? I cannot see it on my system.
